name: Cody Boardman
favicon: null
layout_spectrum: 0.33027909719385207
typography_spectrum: 0.24871898465789855
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9208928477019072
  lightness: 0.36766146472655237
  saturation: 0.5174908286426216
  rhythmicContrast: 0.1346494546160102
purpose: []
